contacto_rest_index:
    path: /contacto/rest/
    controller: App\Controller\ContactoRestController::indexAction
    methods: ["GET"]
    
contacto_rest_new:
    path: /contacto/rest/
    controller: App\Controller\ContactoRestController::newAction
    methods: ["POST"]
    
contacto_rest_show:
    path: /contacto/rest/{contacto_id}
    controller: App\Controller\ContactoRestController::showAction
    methods: ["GET"]
    
contacto_rest_edit:
    path: /contacto/rest/{contacto_id}
    controller: App\Controller\ContactoRestController::editAction
    methods: ["PUT"]
    
contacto_rest_delete:
    path: /contacto/rest/{contacto_id}
    controller: App\Controller\ContactoRestController::deleteAction
    methods: ["DELETE"]
    


